### ISSUE TITLE
Allow gzip compress for BidRequest/BidResponse between prebid server and bidders

### ISSUE THREAD

**Issue by vriffier** [prebid/prebid-server-java#1304]
Hello,

The prebid-server go is implementing this https://github.com/prebid/prebid-server/issues/1812 compression.

Is there any plan on implementing the same thing for the prebid-server-java project?
Are there any bidder who can already read/interpret compressed bidrequest?
Any date on making this available?

Thanks,

**Comment by rpanchyk** [comment]
This one?
https://github.com/prebid/prebid-server-java/pull/1284

**Comment by vriffier** [comment]
No from my understanding you're referring to response decompression whereas I was looking into request compression from PBS to Bidders

**Comment by rpanchyk** [comment]
We've global property for all outgoing requests - https://github.com/prebid/prebid-server-java/blob/master/docs/config-app.md#http-client
So, seems it is not possible to turn on for individual bidder (or request) since PBS uses only a few instances of `HttpClient`.

**Comment by WalterT** [comment]
Hi @rpanchyk, 

Sorry we are a bit unclear here :) 

- Are you saying that it is possible to compress outgoing requests from the server to bidders using http-client.use-compression? Because we tested http-client.use-compression=true and it seems only to be used by bidders to compress their responses but it does not compress outgoing requests. Am I understanding this well? Or is that config supposed to be already compressing outgoing requests?

- If not possible, is this something meant to be implemented here: https://github.com/prebid/prebid-server/issues/1812 ? (Question is for both Go and Java projects).

- Would any bidder be able to read compressed requests?

Thanks a lot for your help and sorry if this is already mentioned somewhere else! We are a bit struggling to be clear on this topic

**Comment by rpanchyk** [comment]
hey @WalterT you're right - let me clarify.

Case 1: `bidder responds to PBS with compressed body` - if you set `http-client.use-compression=true` PBS will add `ACCEPT_ENCODING` header as described here - https://github.com/prebid/prebid-server-java/issues/288#issuecomment-466062325
So, bidder exchange can respond with compressed body and PBS will decompress it.

Case 2: `PBS requests bidder endpoint with compressed body` - this one is not ready yet, but issue you've mentioned (https://github.com/prebid/prebid-server/issues/1812) would be implemented in near future (sorry, no terms so far).
Please follow that issue for any updates on this case.

**Comment by WalterT** [comment]
Hi @rpanchyk,

That's clear, thanks a lot for this!

**Comment by rpanchyk** [comment]
Sure, closing this. Feel free to open new if any.
