### ISSUE TITLE
Support for Prebid Cache Go

### ISSUE THREAD

**Issue by jbartek25** [prebid/prebid-server-java#1359]
Java version of Prebid Cache uses `expiry` for setting item TTL whereas PBC Go uses `ttlseconds`. For anyone who for whatever reason wants to use PBS Java in combination with PBC Go all works fine at the first look but as it turns out since PBS Java sets TTL in `expiry` field and PBC Go ignores it, all items are cached without a TTL (or with the default TTL defined in PBC Go). `ttlseconds` already exists in [PutObject.java](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/cache/proto/request/PutObject.java#L15) so can we have a param to switch between `expiry` and `ttlseconds`. Please see an implementation idea [here](https://github.com/ImproveDigital/prebid-server-java/commit/21d5a220a4e977da64d906a8c0a027f7c12be269).

**Comment by rpanchyk** [comment]
hi @jbartek25 
Thanks for bringing up!

Looking into PBC-Java i see it can work with both `expiry` and `ttlseconds`: https://github.com/prebid/prebid-cache-java/blob/master/src/main/java/org/prebid/cache/model/PayloadTransfer.java#L31

So, at first glance - we can use `ttlseconds` instead of `expiry` in API for PBC-Java without any issues.

@bretg Are any objections on that which i may missed?

**Comment by bretg** [comment]
No objections @rpanchyk - I prefer `ttlseconds`, which is what PBJS sends.

**Comment by rpanchyk** [comment]
Merged. Closing this.

**Comment by bretg** [comment]
released with PBS-Java 1.69
