### ISSUE TITLE
Unable to run Groovy test cases

### ISSUE THREAD

**Issue by eshaanmangal** [prebid/prebid-server-java#1794]
Hi team, I just took a fresh pull of prebid-server-java, and when I tried to run Groovy test cases, I am getting Errors (Screenshot attached). The only thing that is different in my repo (ref master) is that in pom.xml I have enabled "launchContainers".  The issue is that the code is trying to fetch "prebid/prebid-server: latest" as timing out eventually.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/35827250/160770463-a97f9e3d-8f97-4b45-b040-2460e3482314.png">

**Comment by Net-burst** [comment]
Hi. This happens because you didn't build an image. Tests rely on Docker image being present and until you either run `maven clean verify` which will build it automatically to run the tests or build it yourself by running `maven clean package docker:build`. Both commands will leave a PBS docker image in your local registry. There is a PR with the documentation which will be merged soon: https://github.com/prebid/prebid-server-java/pull/1755

**Comment by eshaanmangal** [comment]
Thanks a lot @Net-burst
