### ISSUE TITLE
Asynchronous batch catching mechanism

### ISSUE THREAD

**Issue by az-auddin** [prebid/prebid-server-java#1944]
### Objective
Current Prebid Server Java implementation performs a blocking HTTP call to Prebid Cache to cache VAST XML from SSPs. For this caching, PBS deducts `cache.expected-request-time-ms` from `tmax` (our current prod setting is 25ms). We would like to introduce a new async caching mode (enabled via a new boolean param, e.g. `cache.async-caching.enabled`). When enabled, PBS will first generate the item cache keys that PBC will use for caching and after issuing cache write request, PBS won’t wait for the PBC response, assuming the PBC will manage to cache the items before the client receives the bid response and attempts to access the cache. In our testing this works well, effectively reducing `cache.expected-request-time-ms` to 0 and allowing more time for the bidders to respond with the same `tmax`.

### Implementation Proposal
**Batching**
Rather than, saving to prebid-cache server synchronously, we queue `List<PutObject>` and send bulk requests through periodic service.

**Workflow**
_Abstracting cache layer_
![01-abstracting-cache layer](https://user-images.githubusercontent.com/94958976/178430487-d1612c2b-978e-4204-adb0-d8faa62cbd42.jpeg)

_Implementing asynchronous batch_
![02-implementing-asynchronous-batch](https://user-images.githubusercontent.com/94958976/178430517-a1d6251e-3dca-4505-b245-f8584b6971c8.jpeg)

Finally, we would like to know your opinion on this about better approach to solve the problem; any other alternative or tweaking on this approach. Can it be considered as new feature in the main stream of prebid-server-java? We are happy to contribute :)

Thanks.

**Comment by bretg** [comment]
Thanks for the thoughts here @az-auddin - will discuss with the team.

**Comment by SyntaxNode** [comment]
We discussed the issue at the Prebid Server PMC and have identified some concerns:

1. If the PBC async batch fails, a bid was already returned which would later fail to render. We might be able to mitigate this concern with a retry.
2. This approach introduces a race condition between rendering the ad and the batched cache call to PBC which may result in a winning bid failing to render. We cannot think of a possible mitigation.
3. Due to the high throughput of PBS, we are concerned how much memory would be required for the batches (assuming this is across multiple different auctions).

Is the current behavior causing you a problem? Have you seen significant improvement by removing the 25ms time deducted?

Perhaps you can also fine tune your PBC backend and further reduce the time deducted?

**Comment by jbartek25** [comment]
We re-considered the approach and implemented the async caching without the batching mechanism: PBS doesn't wait for PBC to respond but rather responds back to the client immediately. @az-auddin this issue can be closed.

**Comment by bretg** [comment]
@jbartek25 - was there a pull request to an open source repo related to this?

**Comment by jbartek25** [comment]
@bretg there wasn't a PR. We implemented it in our fork but are happy to contribute to the main repo if this feature is desired.
