### ISSUE TITLE
Port 8090 already in use error 

### ISSUE THREAD

**Issue by nimeshbansal22** [prebid/prebid-server-java#2022]
When we are building the latest tag of prebid server java ( tag 1.97.0 ) there are certain random failures of test cases which shows that the port 8090 is already in use.

The stack trace shows as follows:-

-------------------------------------------------------------------------------
Test set: org.prebid.server.it.VidoomyTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in org.prebid.server.it.VidoomyTest
org.prebid.server.it.VidoomyTest Time elapsed: 0.005 s <<< ERROR!
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8090
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8090
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:8090
Caused by: java.net.BindException: Address already in use

The Java and maven version used were:- 

Java version:- 17.0.4.1
Maven version:- 3.8.4

**Comment by Net-burst** [comment]
Hello, @nimeshbansal22 . Unfortunately this is a known issue and it's impossible to fix without overcomplicating test infrastructure. This happens due to WireMock not surviving frequent relaunches, which is most likely happening due to old Netty. We have plans to update all of the dependencies soon, so this issue should go away as the more recent Netty versions should have that fixed.
If you will have further questions, please feel free to open a new issue. Or if you will find a good temporary solution, feel free to submit a PR. Thanks.
