### ISSUE TITLE
Cookie Sync gen/matches metrics got remove

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#2114]
Hi,

In #2065 two valuable metrics were removed

- `cookie_sync.<adapter>.gen`
- `cookie_sync.<adapter>.matches`

We used to calculate a match/gen rate "matches / gen" by bidder to see how much cookies are being generated or matched. Digging deeper into this, I fear that we misinterpreted the metrics. However we used them only to validate "hey, this bidder cookie sync is actually doing something".

Is this something that should be inserted again?

Related issue: https://github.com/prebid/prebid-server/issues/2173

**Comment by bretg** [comment]
Thanks for bringing this up @muuki88 . How would you define these metrics? `gen` seems obvious enough. But what does `matched` mean? I would argue that the 'usersync' metrics are really more important -- those are the ones generated by /setuid. The new sizeblocked and sizedout metrics are quite interesting. 

> "hey, this bidder cookie sync is actually doing something".

Perhaps that can be satisfied with `usersync.*.sets`?

Stepping back, here are the set of metrics I could find for the two endpoints:

/cookie_sync endpoint
- cookie_sync.FAMILY.filtered - due to an image or iframe filter
- cookie_sync.FAMILY.tcf.blocked - required consent but didn't have it
- cookie_sync_requests - number of times the endpoint is hit
- ? cookie_sync.FAMILY.gen - how many times a given adapter's sync was returned
- ? cookie_sync.FAMILY.matches - ?

/setuid endpoint
- usersync.opt_outs - ?
- usersync.bad_requests - invalid calls to /setuid
- usersync.FAMILY.sets - how many times a given adapter had an ID added to the uids cookie
- usersync.FAMILY.tcf.blocked - how many times a given adapter's set request was blocked due to valid GDPR permissions that didn't grant consent
- usersync.FAMILY.tcf.invalid - how many times a given adapter's set request was blocked due to invalid GDPR permissions
- usersync.FAMILY.sizeblocked - how many times a given adapter wasn't able to add its ID to the cookie because the cookie was full.
- usersync.FAMILY.sizedout - how many times a given adapter was kicked out of the cookie because a "priority" adapter needed to get in.

**Comment by muuki88** [comment]
My assumption was that `matches` means "the cookie sync request contains already an ID for this adapter".

I agree that the Usersync metrics are more important and should already solve our problem 😊

**Comment by bretg** [comment]
So would you like these metrics to be restored @muuki88 , or just close this issue?

**Comment by muuki88** [comment]
I'm going for close 🤗
