### ISSUE TITLE
PBS-java proto compiled files are not being seen by IDE

### ISSUE THREAD

**Issue by xzhaoxz** [prebid/prebid-server-java#2398]
Why there is an error that prevents importing the com.iabtechlab.openrtb.v2.OpenRtb class when cloning prebid-server-java from GitHub?

![image](https://github.com/prebid/prebid-server-java/assets/132535817/6c749976-2c2d-41d4-8c42-c5ced4be36df)

**Comment by SerhiiNahornyi** [comment]
Looks like you are using Intellij to work with code, 
files created by proto compiler are too big by default to be read by IDE

@And1sS Pls provide required IDE setting to make everything work as expected

**Comment by And1sS** [comment]
@xzhaoxz Hi!

First of all, you need to compile these files. They are compiled from `.proto` files located in `src.main.proto`. This can be done by running `mvn protobuf:compile` command in your terminal, or by clicking in Intellij IDEA:
`maven > prebid-server > Plugins > protobuf > protobuf:compile`.
P.S. This is done as a `compile`(and `test-compile` for tests) step of maven if you build app using maven directly.

After that you can already build and run an application via IntelliJ IDEA. But Intellij IDEA will not recognize these files with its default settings yet, and will still report error even though application can be compiled. This is because intellisense does not introspect large files by default (and compiled classes from proto files are huge compared to default classes).

Here is how to resolve this:
In IntelliJ IDEA click `Help > Edit custom properties...` and add this property in kilobytes `idea.max.intellisense.filesize=your-value-here`. I personally use 200000 (e.g. `idea.max.intellisense.filesize=200000`) and it works fine.
More about this property here: https://www.jetbrains.com/help/objc/configuring-file-size-limit.html

This is not first time someone struggles to build prebid-server-java after we have added support for protobuf model, so I will update README to include this guide. Thanks for reporting!

**Comment by xzhaoxz** [comment]
Thank you for your help, the issue has been resolved

**Comment by xzhaoxz** [comment]
I have a new question and hope to get an answer. Now I want to build my own PBS by reading the documentation, but I have some confusion about the Global Load Balancer, Regional Load Balancers, and Replicated Database components. Do I need to implement these three components myself? For example, can I use ZK or Nacos to implement Load Balancer? Is the Source Database that the Replicated Database synchronizes an advertiser’s database?
![image](https://github.com/prebid/prebid-server-java/assets/132535817/bd7ad535-c3f3-4d3f-9d84-1260e8d6c02b)

**Comment by xzhaoxz** [comment]
There is an error in the build.md file. It requires JDK 11, but the actual project currently uses JDK 17.

**Comment by xzhaoxz** [comment]
I have a new question and hope to get an answer. From reading the documentation, I now want to build my own PBS with components including the source database and Replicated database. However, the prebid-server-java only has operations related to the Account Configuration settings for the database and there are no table creation statements for the Replicated database. Can you describe the specific roles of the source database and Replicated database, and how I should implement them?

**Comment by xzhaoxz** [comment]
Is the Replicated Database responsible for handling Stored Requests? In other words, can advertisers send pre-packaged ad requests to Prebid Server according to a predefined request specification, and then Prebid Server stores these requests in the Replicated Database? Later on, when Prebid Server receives an ad request, it searches for a matching predefined request specification in the stored requests. If found, Prebid Server uses the stored request parameters and matching parameters to generate a real-time ad request. Otherwise, it generates a real-time ad request in the normal way.

**Comment by And1sS** [comment]
@xzhaoxz Prebid Server does not store anything, it just reads data from database. Stored Requests/Auctions, account configs, etc.

**Comment by bretg** [comment]
@xzhaoxz - please see https://docs.prebid.org/prebid-server/hosting/pbs-database.html for info about the DB. (note that a replicated DB would most likely have the same schema as the source DB)

**Comment by xzhaoxz** [comment]
Thank you for your help，I understand Replicated Database.

**Comment by xzhaoxz** [comment]
Do we always need a Stored Request, and are all requests sent by SDK Stored Requests? Must PBS store Stored Requests and Stored Responses? If it is mandatory, is the format of all Stored Requests uniform (same JSON format and fields with different parameter values)?

**Comment by xzhaoxz** [comment]
After reading the code, I found that the property “hasStoredBidRequest” of the AuctionStoredResult class can be set to false, which means that the request sent can be made without a stored request. If the SDK sends a standard OpenRTB request, it may not require Stored Request, so Stored Request is not mandatory. 
After confirming this with ChatGPT, I received the following response: Stored Request is not mandatory in prebid-server-java, but it may be very useful for certain specific functions of prebid-server-java. prebid-server-java supports two types of requests: standard OpenRTB requests and prebid-server-native requests. For standard OpenRTB requests, Stored Request is not required because each OpenRTB request will contain all the necessary parameters and values. However, for prebid-server-native requests, Stored Request can store application-specific JSON objects and reference them by their ID. The advantage of having Stored Request is that it can reduce the load on prebid-server-java, as multiple duplicate requests can be pre-processed and saved to the database. In addition, storing requests also allows applications to add custom data to requests and make requests more flexible. Therefore, Stored Request may be very useful for certain applications in prebid-server-java, but it is not mandatory. 
Please confirm if my understanding of Stored Request is correct.

**Comment by bretg** [comment]
I'd give ChatGPT 85% on that answer. :-)

It's correct that stored requests are not mandatory. In fact Prebid.js doesn't (generally) use them at all and SDK/JS share the same protocol endpoint.

But for SDK, you'd be kinda silly to **not** utilize stored requests -- once a mobile app is live in the wild, it's hard to upgrade. You don't want to hardcode bidders and bid parameters in an SDK because those things can change frequently. The whole point of stored requests is so that the Ad Ops team can evolve the bidders without pushing app updates. https://docs.prebid.org/prebid-server/features/pbs-storedreqs.html - I'll emphasize this point more in the documentation.

Are we ready to close this issue?
