### ISSUE TITLE
Adding user ID processing in Prebid Server?

### ISSUE THREAD

**Issue by sunnywu** [prebid/prebid-server-java#2834]
Hi,

I am reading thru the prebid server documentation and i would like to understand what changes i need to make if I as a publisher with a prebid server setup - When I send bid request to the prebid server, it will run some codes to generate new user ids (e.g. RampID, ID5, UnifiedID2.0) on prebid server and append it into the bid request into the bid adapters to then forward the requests to various Demand partners. 

How should I go about implementing the above? I can see there is auction post-processing hook but i don't see any outgoing bid request hook that i can use.

Thanks.

**Comment by bretg** [comment]
@sunnywu - there are not yet any ID vendors that have chosen to create modules for Prebid Server. It's one of our goals for 2024 to engage with some. The issue of course is that cookies/local-storage doesn't exist server-side, which is why ID vendors tend to operate there.

If you're with a company who can help with this, we're definitely interested in consulting with you on an implementation. See https://docs.prebid.org/prebid-server/developers/add-a-module.html for the 7 stages where modules can take action.

**Comment by bretg** [comment]
I'm in discussion with Sunny and others on building out a Prebid Server module.

If any other vendors would like to discuss the possibility of porting a module to Prebid Server, please reach out to me or open an issue.
